"""empty message

Revision ID: 1800fa931b63
Revises: 
Create Date: 2023-11-24 12:14:22.574898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1800fa931b63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=260), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('insured_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=260), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('insurances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('i_person_id', sa.Integer(), nullable=True),
    sa.Column('insurance_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('insured_item', sa.String(length=60), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_till', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['i_person_id'], ['insured_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurances')
    op.drop_table('insured_persons')
    op.drop_table('users')
    # ### end Alembic commands ###
